import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { db } from "@/lib/db";
import { workspaceMembers, workspaces } from "@/lib/db/schema";
import { and, eq } from "drizzle-orm";
import { getStorageProvider } from "@/lib/storage/factory";

/**
 * POST /api/upload
 *
 * Handles client-side file uploads for local storage provider.
 * For S3, clients upload directly using presigned URLs.
 *
 * Query params:
 * - key: Storage key (workspaceSlug/cuid/filename)
 * - workspaceSlug: Workspace identifier
 *
 * Body: Raw file buffer
 * Content-Type header: File MIME type
 */
export async function POST(req: NextRequest) {
  try {
    // 1. Verify authentication
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // 2. Get query parameters
    const { searchParams } = new URL(req.url);
    const key = searchParams.get("key");
    const workspaceSlug = searchParams.get("workspaceSlug");

    if (!key || !workspaceSlug) {
      return NextResponse.json(
        { error: "Missing required parameters: key, workspaceSlug" },
        { status: 400 }
      );
    }

    // 3. Verify workspace exists and user is a member
    const workspace = await db.query.workspaces.findFirst({
      where: eq(workspaces.slug, workspaceSlug),
    });

    if (!workspace) {
      return NextResponse.json(
        { error: "Workspace not found" },
        { status: 404 }
      );
    }

    const membership = await db.query.workspaceMembers.findFirst({
      where: and(
        eq(workspaceMembers.workspaceId, workspace.id),
        eq(workspaceMembers.userId, session.user.id)
      ),
    });

    if (!membership) {
      return NextResponse.json(
        { error: "Not a member of this workspace" },
        { status: 403 }
      );
    }

    // 4. Get file from request body
    const buffer = Buffer.from(await req.arrayBuffer());

    // 5. Get content type from header
    const contentType =
      req.headers.get("content-type") || "application/octet-stream";

    // 6. Save file directly using the pre-generated key
    // The key was already generated by getUploadUrl() and must match
    const provider = getStorageProvider();

    // For local storage, manually save to the exact path specified by key
    const path = await import("path");
    const { writeFile, mkdir } = await import("fs/promises");

    const uploadsDir = path.join(process.cwd(), "public", "uploads");
    const filePath = path.join(uploadsDir, key);
    const fileDir = path.dirname(filePath);

    // Ensure directory exists
    await mkdir(fileDir, { recursive: true });

    // Write file
    await writeFile(filePath, buffer);

    const url = `/uploads/${key}`;

    return NextResponse.json({ url, key });
  } catch (error) {
    console.error("Upload error:", error);
    return NextResponse.json(
      { error: "Failed to upload file" },
      { status: 500 }
    );
  }
}
